/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "us-east-2",
  aws_cognito_identity_pool_id:
    "us-east-2:a3f03ab0-0c54-44a9-aedf-cfbf0f5104db",
  aws_cognito_region: "us-east-2",
  aws_user_pools_id: "us-east-2_lYFvK3ND7",
  aws_user_pools_web_client_id: "5ijapgg0ue3sv2p30m0a6n4fgp",
  oauth: {},
  aws_appsync_graphqlEndpoint:
    "https://nnrakggy2fcpdkplybi4j32sma.appsync-api.us-east-2.amazonaws.com/graphql",
  aws_appsync_region: "us-east-2",
  aws_appsync_authenticationType: "API_KEY",
  aws_appsync_apiKey: "da2-4hgp52avz5a7jmkn65obobrljm",
};

export default awsmobile;
