/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:1403b97c-dc87-4262-be8b-c3a5fa4177cb",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_ST4zqTDmY",
    "aws_user_pools_web_client_id": "11ks7uni6ks1mg0v74pp7q4khn",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://nnrakggy2fcpdkplybi4j32sma.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-4hgp52avz5a7jmkn65obobrljm"
};


export default awsmobile;
